In [51]:
import numpy as np
import pandas as pd

#import urllib.request

import sklearn
from mixed_naive_bayes import MixedNB
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split

from sklearn import metrics
from sklearn.metrics import accuracy_score

# Import LabelEncoder
from sklearn import preprocessing

In [52]:
dataset = pd.read_csv('Fertility1.csv', sep=';')

In [53]:
dataset.shape

(100, 10)

In [54]:
dataset.head(20)

,season,age,Ch_Disease,Accident,Surg_Int,H_Fever,Alcohol_Cons,Smoke,N_Hours,Diag
0,Fall,30,No,Yes,Yes,Greater th 3m,Once a week,Daily,6,Altered
1,Winter,31,No,Yes,No,No,Several times a week,Occasional,9,Normal
2,Winter,29,No,Yes,No,Greater th 3m,Hardly ever or never,Occasional,3,Normal
3,Fall,30,No,Yes,No,Greater th 3m,Once a week,Never,4,Altered
4,Spring,30,No,No,Yes,Greater th 3m,Once a week,Never,8,Altered
5,Winter,28,No,Yes,Yes,Greater th 3m,Hardly ever or never,Never,7,Normal
6,Fall,29,Yes,Yes,No,Greater th 3m,Once a week,Never,4,Normal
7,Spring,27,No,No,Yes,Less th 3m,Once a week,Occasional,14,Altered
8,Spring,34,No,No,Yes,Greater th 3m,Several times a week,Daily,5,Normal
9,Winter,30,No,Yes,Yes,Greater th 3m,Hardly ever or never,Never,8,Normal
10,Fall,30,No,No,Yes,Less th 3m,Once a week,Occasional,5,Normal
11,Spring,29,No,No,No,Greater th 3m,Once a week,Never,5,Normal
12,Winter,27,No,No,No,Greater th 3m,Once a week,Daily,8,Normal
13,Winter,32,No,Yes,No,No,Hardly ever or never,Daily,4,Normal
14,Winter,30,Yes,Yes,No,Greater th 3m,Several times a week,Occasional,8,Altered
15,Winter,27,No,Yes,Yes,No,Once a week,Never,5,Normal
16,Spring,28,No,No,Yes,Greater th 3m,Every day,Daily,10,Normal
17,Winter,30,No,No,No,No,Once a week,Never,3,Normal
18,Spring,34,No,Yes,Yes,No,Several times a week,Never,3,Normal
19,Fall,28,No,No,No,Greater th 3m,Once a week,Occasional,7,Normal

In [55]:
#labelEncoder
le = preprocessing.LabelEncoder()

# Converting string labels into numbers.
dataset['season_cd']=le.fit_transform(dataset.loc[:, 'season'])
dataset['Ch_Disease_cd']=le.fit_transform(dataset.loc[:, 'Ch_Disease'])
dataset['Accident_cd']=le.fit_transform(dataset.loc[:, 'Accident'])
dataset['Surg_Int_cd']=le.fit_transform(dataset.loc[:, 'Surg_Int'])
dataset['H_Fever_cd']=le.fit_transform(dataset.loc[:, 'H_Fever'])
dataset['Alcohol_Cons_cd']=le.fit_transform(dataset.loc[:, 'Alcohol_Cons'])
dataset['Smoke_cd']=le.fit_transform(dataset.loc[:, 'Smoke'])
dataset['Diag_cd']=le.fit_transform(dataset.loc[:, 'Diag'])

In [56]:
dataset = dataset.drop(['season', 'Ch_Disease', 'Accident', 'Surg_Int', 'H_Fever', 'Alcohol_Cons', 'Smoke', 'Diag'], axis=1)

In [57]:
dataset.shape

(100, 10)

In [58]:
X = dataset.loc[:, dataset.columns != 'Diag']
y = dataset.loc[:, dataset.columns == 'Diag']

In [59]:
X.head()

,age,N_Hours,season_cd,Ch_Disease_cd,Accident_cd,Surg_Int_cd,H_Fever_cd,Alcohol_Cons_cd,Smoke_cd,Diag_cd
0,30,6,0,0,1,1,0,2,0,0
1,31,9,3,0,1,0,2,4,2,1
2,29,3,3,0,1,0,0,1,2,1
3,30,4,0,0,1,0,0,2,1,0
4,30,8,1,0,0,1,0,2,1,0

In [60]:
#X = pd.array(dataset.iloc[:,0:5])
X_train = dataset.iloc[0:80, 0:9].to_numpy()
y_train = dataset.iloc[0:80, 9].to_numpy()

X_test = dataset.iloc[81:, 0:9].to_numpy()
y_test = dataset.iloc[81:, 9].to_numpy()

In [62]:
clf = MixedNB(categorical_features=[2, 3, 4, 5, 6, 7, 8])
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print(accuracy_score(y_test, y_pred))

[4 2 2 2 3 5 3]
0.9473684210526315